<?xml version="1.0"?>
<robot name="jo_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find my_robot_description)/urdf/my_robot.gazebo" />

  <link name="base_footprint" />

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>

  <xacro:property name="pi" value="3.1415926535897931" />
  <xacro:property name="base_width" value="0.1" />
  <xacro:property name="base_length" value="0.2" />
  <xacro:property name="base_height" value="0.005" />
  <xacro:property name="wheel_diameter" value="0.1" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="wheel_offset" value="0.005" />
  <xacro:property name="caster_wheel_diameter" value="${wheel_diameter/2}" />
  <xacro:property name="pillar_width" value="0.002" />
  <xacro:property name="pillar_length" value="0.002" />
  <xacro:property name="pillar_height" value="0.05" />
  <xacro:property name="laser_radius" value="0.03" />
  <xacro:property name="laser_height" value="0.04" />
  

  <xacro:macro name="box_inertia" params="m x y z">
          <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                    iyy="${m*(x*x+z*z)/12}" iyz = "0"
                    izz="${m*(x*x+z*z)/12}" /> 
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
      <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                    iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                    izz="${m*r*r/2}" /> 
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
          <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                    iyy="${2*m*r*r/5}" iyz = "0"
                    izz="${2*m*r*r/5}" /> 
  </xacro:macro>

  <xacro:macro name="box_inertial" params="m x y z">
    <inertial>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <mass value="${m}" />
      <xacro:box_inertia m="${m}" x="${x}" y ="${y}" z="${z}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertial" params="m r h">
    <inertial>
      <mass value="${m}" />
      <xacro:cylinder_inertia m="${m}" r="${r}" h="${h}" />
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertial_sensor" params="m r h">
    <inertial>
      <mass value="${m}" />
      <xacro:cylinder_inertia m="${m}" r="${r}" h="${h}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertial" params="m r">
    <inertial>
      <mass value="${m}" />
      <xacro:sphere_inertia m="${m}" r="${r}" />
    </inertial>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}" />
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}" />
      </geometry>
    </collision>
    <xacro:box_inertial m="5" x="${base_width}" y="${base_length}" z="${base_height}"/>
  </link>

  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
        <material name="White">
          <color rgba="1.0 1.0 1.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial m="1" r="${wheel_diameter/2}" h="${wheel_width}"/>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="-1 0 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${reflect * base_width/2 + reflect * wheel_width/2 + reflect * wheel_offset} ${-base_length*0.333} 0" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <xacro:wheel prefix="left" reflect="-1" />
  <xacro:wheel prefix="right" reflect="1" />

  
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${wheel_diameter/4}" />
      </geometry>
      <material name="White" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_diameter/4}" />
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <xacro:sphere_inertial m="5" r="${caster_wheel_diameter}"/>
  </link>

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0 ${base_length/9*3} ${-caster_wheel_diameter/2}" rpy="0 0 0"/>
  </joint>
  

  <xacro:macro name="front_pillar" params="prefix reflect">
    <link name="${prefix}_front_pillar">
      <visual>
        <geometry>
          <box size="${pillar_width} ${pillar_length} ${pillar_height}" />
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${pillar_width} ${pillar_length} ${pillar_height}" />
        </geometry>
      </collision>
    <xacro:box_inertial m="1" x="${pillar_width}" y="${pillar_length}" z="${pillar_height}"/>
    </link>
    <joint name="${prefix}_front_pillar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_front_pillar"/>
      <origin xyz="${reflect * base_width/2 - reflect * wheel_offset * 0.5} ${base_length*0.5 - wheel_offset * 0.5} ${pillar_height/2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="back_pillar" params="prefix reflect">
    <link name="${prefix}_back_pillar">
      <visual>
        <geometry>
          <box size="${pillar_width} ${pillar_length} ${pillar_height}" />
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${pillar_width} ${pillar_length} ${pillar_height}" />
        </geometry>
      </collision>
    <xacro:box_inertial m="1" x="${pillar_width}" y="${pillar_length}" z="${pillar_height}"/>
    </link>
    <joint name="${prefix}_back_pillar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_back_pillar"/>
      <origin xyz="${reflect * base_width/2 - reflect * wheel_offset * 0.5} ${-base_length*0.5 + wheel_offset * 0.5} ${pillar_height/2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:front_pillar prefix="left" reflect="-1" />
  <xacro:front_pillar prefix="right" reflect="1" />
  <xacro:back_pillar prefix="left" reflect="-1" />
  <xacro:back_pillar prefix="right" reflect="1" />

  <link name="top_link">
    <visual>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}" />
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}" />
      </geometry>
    </collision>
    <xacro:box_inertial m="5" x="${base_width}" y="${base_length}" z="${base_height}"/>
  </link>

  <joint name="top_link_joint" type="fixed">
      <parent link="left_back_pillar"/>
      <child link="top_link"/>
      <origin xyz="${1 * base_width/2 - 1 * wheel_offset * 0.5} ${base_length*0.5 - wheel_offset * 0.5} ${pillar_height/2}" rpy="0 0 0"/>
  </joint>



   <link name="laser_scanner_link">
      <xacro:cylinder_inertial_sensor m="1" r="${laser_radius}" h="${laser_height}"/>
  
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
        </geometry>
        <material name="White" />
    </visual>

    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
        </geometry>
    </collision>
    </link>

    <joint name="laser_scanner_joint" type="fixed">
    <origin xyz="0 ${base_length*0.25} ${laser_height/2}" rpy="0 0 0"/>
    <parent link="top_link"/>
    <child link="laser_scanner_link"/>
  </joint>

  
  <!-- This block connects the wheel joint to an actuator (motor), which informs both
    simulation and visualization of the robot 
    <transmission name="left_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="left_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="left_wheel_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>

    <transmission name="right_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="right_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="right_wheel_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>-->

  <!-- Gazebo plugin for ROS Control -->
  

</robot>
